{% set name = "lazy-imports" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lazy_imports-{{ version }}.tar.gz
  sha256: 3c546b3c1e7c4bf62a07f897f6179d9feda6118e71ef6ecc47a339cab3d2e2d9

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - lazy_imports
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bachorp/lazy-imports
  summary: Tool to support lazy imports
  description: |
    lazy-imports provides utilities for deferred module loading in Python,
    reducing startup time by only importing modules when they are first accessed.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/bachorp/lazy-imports
  dev_url: https://github.com/bachorp/lazy-imports

extra:
  recipe-maintainers:
    - rxm7706
